language: node_js
node_js:
  - '8'
addons:
  apt:
    packages:
      - docker-ce
env:
  - DOCKEST_CI=true

before_install:
  # print relevant versions
  - docker --version
  - docker-compose --version

  # upgrading docker-compose to match Dockest's development version: v1.23.2
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

  # pull example images
  - cd example
  - docker-compose -f docker-compose-dockest.yml pull
  - cd ../

  - yarn global add typescript

  - echo "*** <travis.before_install> complete ***"
install:
  - yarn travis:install

  - echo "*** <travis.install> complete ***"
script:
  # generate typedoc markdown files
  - yarn travis:docs

  # publish docusaurus website
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website
  - GIT_USER="${GH_NAME}" yarn publish-gh-pages
  - cd ../

  # - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  # - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - yarn travis:script
