language: node_js
node_js:
  - '8'
addons:
  apt:
    packages:
      - docker-ce
env:
  - DOCKEST_CI=true

before_install:
  # print relevant versions
  - docker --version
  - docker-compose --version
  - yarn --version

  # upgrading docker-compose to match Dockest's development version: v1.23.2
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

  - yarn global add typescript

  - echo "*** <travis.before_install> complete ***"
install:
  - yarn
  - yarn prepare-packages

  - echo "*** <travis.install> complete ***"
script:
  - yarn lint

  # generate typedoc markdown files
  - yarn generate:typedoc

  # publish docusaurus website on commits to master
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    git config --global user.name "${GH_NAME}";
    git config --global user.email "${GH_EMAIL}";
    echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc;
    cd website;
    yarn;
    GIT_USER="${GH_NAME}" yarn publish-gh-pages;
    cd ../;
    fi

  # - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  # - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - yarn test
